version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    container_name: product-service
  mongo:
    image: "mongo:latest"
    container_name: mymongodb

networks:
 default:
   external:
     name: product-review-service      